<a href="https://colab.research.google.com/github/skflwright/learning_rep/blob/main/1_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NumPy (or Numpy) is a Pyhton Library or Module design for Linear Algebra and Statistical Computation.
It is one of the most important modules in python for Data Science since most all of the libraries necessary for  rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to other programming language libraries such as C++.

_______________________________

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We will not have the time to cover them all; we will, however, focus on some of the most important topics such as vectors, arrays, matrices, and number generation. Let's start by discussing arrays.

## Numpy Arrays

NumPy arrays are the main objects that we will use in this class.

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional arrays and matrices are 2-dimensional (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

### Creating NumPy Arrays From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,110,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(5)
# I do not know what this means!!!
# np --> numpy
#


array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((15,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [ ]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((30,30))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(5)

array([0.42471055, 0.11006601, 0.44520398, 0.32604911, 0.73036708])

In [ ]:
np.random.rand(10,10)

array([[0.38189437, 0.95793753, 0.53331906, 0.71088667, 0.09710979,
        0.36884686, 0.45119516, 0.1621456 , 0.80486657, 0.83470798],
       [0.05705046, 0.16400136, 0.7636192 , 0.38377103, 0.93160694,
        0.79941759, 0.98908733, 0.4489359 , 0.48462952, 0.25184888],
       [0.8452552 , 0.00438507, 0.60765651, 0.57057192, 0.55798256,
        0.90308538, 0.13595867, 0.43274963, 0.86251335, 0.03459715],
       [0.85307554, 0.76527575, 0.13524692, 0.76527622, 0.17997505,
        0.75474365, 0.08400477, 0.59952248, 0.04655282, 0.94687287],
       [0.03582308, 0.54629897, 0.84841464, 0.92138407, 0.22219919,
        0.92420974, 0.60520087, 0.44708124, 0.18156705, 0.32064048],
       [0.82322974, 0.09907   , 0.50123916, 0.4025846 , 0.13229108,
        0.93816279, 0.50198879, 0.34024473, 0.07671343, 0.29935109],
       [0.97522612, 0.2835161 , 0.21301877, 0.56303248, 0.87200994,
        0.33785549, 0.82282758, 0.14699804, 0.10078724, 0.83185482],
       [0.18366508, 0.07897272, 0.8900855

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(20)

array([-1.34093505,  0.94791757,  0.1395064 , -1.40495145, -1.59332205,
       -0.01753231,  0.6623276 ,  0.44555128, -1.05195843,  0.38625572,
       -0.22778826,  0.53858752, -1.83104742,  0.68793464, -0.21569953,
        2.23665613, -0.36863519,  0.2932144 , -1.13955031,  0.62407605])

In [ ]:
np.random.randn(5,5)

array([[-2.71563949,  0.35478281,  1.09249821,  0.79076392,  0.69165734],
       [ 0.49475927, -0.73884058,  0.64332548, -0.94331314, -0.88127794],
       [-1.8365377 , -0.84652957,  0.58539482,  0.04647664, -0.08514569],
       [ 0.48033337,  0.29305124,  1.34182153,  0.40658894,  0.03279596],
       [ 1.82260817, -0.22822687,  0.57531245, -0.22714078,  0.10486562]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,500)

128

In [ ]:
np.random.randint(1,1000,100)

array([950, 481, 962, 573, 576, 796, 621, 863, 986, 236, 725,  78, 770,
       837, 395, 929, 242, 236, 898, 864, 962, 415, 184, 530,  46, 243,
       153, 816, 535,  40,  13, 111, 102, 734,  35, 646, 433, 687,  33,
       591, 653, 218, 357, 341,  96, 867, 533, 935, 618, 689, 974, 621,
       265, 738, 918, 730, 653,  28, 425, 700, 509, 715, 914, 811, 668,
       236, 372,  14, 880, 670, 130,  26, 901, 117, 473, 398, 948, 456,
       792, 720, 892, 103, 452, 463, 206, 621, 990, 537, 481, 709, 928,
       382, 879, 813, 355, 188, 968, 829,  71, 685])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(50)
ranarr = np.random.randint(0,500,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
ranarr

array([497, 191,  95, 121, 395, 121, 279, 107, 362,  43])

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([497, 191,  95, 121, 395, 121, 279, 107, 362,  43])

In [ ]:
ranarr.max()

497

In [ ]:
ranarr.argmax()

0

In [ ]:
ranarr.min()

43

In [ ]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(50,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr.reshape(2,25).shape

(2, 25)

In [ ]:
arr.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [ ]:
arr.reshape(25,2).shape

(25, 2)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

# Good Times!